FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

RUN mkdir /planet
WORKDIR /planet

COPY requirements.txt /planet/requirements.txt
RUN pip install --no-cache-dir -r /planet/requirements.txt

COPY code   /planet/code
COPY config /planet/config
COPY static /planet/static
